/*
 * generated by Xtext
 */
package me.qfdk.esir.wh;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class WhUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return me.qfdk.esir.wh.ui.internal.WhActivator.getInstance().getInjector("me.qfdk.esir.wh.Wh");
	}
	
}
